### PR TITLE
flash using jLink using makeFile

### PR DESCRIPTION
**Pull request by trns1997**
This is still a WIP. The plan I have is to create a `build.sh` and `flash.sh` to build and flash our targets. But this first commit already allows us to flash the XMC board from a simple `make flash` command

### CODE REVIEW

**Comment by cedricq** [comment]
image

It takes forever in Erasing flash ...

**Comment by cedricq** [comment]
The command `./build.sh XMC4800-2048 ankle relax` does not work :(

**Comment by cedricq** [comment]
> The command
> 
> ```
> ./build.sh XMC4800-2048 ankle relax` does not work
> ```

I reopened a terminal and the build worked again ....

**Comment by cedricq** [comment]
Funny thing: 
- when I flash ankle product ankle board on a relax board, the 2 Ethernet ports LEDs are ON.
- when I flash ankle product relax board on a relax board, the 2 Ethernet ports LEDs are OFF.

Do you know what's wrong ?

**Comment by cedricq** [comment]
Weird thing:
- On both ankle/ankle and ankle/relax on a relax board, once flashing is completed, LED P5.9 turns ON for ~15s then turns OFF forever.
- On both ankle/ankle on a relax board only, LED5 P1.2 turns ON but not ankle/relax on a relax board

**Comment by cedricq** [comment]
> Funny thing:
> 
>     * when I flash ankle product ankle board on a relax board, the 2 Ethernet ports LEDs are ON.
> 
>     * when I flash ankle product relax board on a relax board, the 2 Ethernet ports LEDs are OFF.
> 
> 
> Do you know what's wrong ?

I was not able to reproduce it... Weird ...

**Comment by trns1997** [comment]
Yea erase takes a little time as it erases all sectors of the chips. We could do without erase but its better.

**Comment by trns1997** [comment]
> Weird thing:
> 
>     * On both ankle/ankle and ankle/relax on a relax board, once flashing is completed, LED P5.9 turns ON for ~15s then turns OFF forever.
> 
>     * On both ankle/ankle on a relax board only, LED5 P1.2 turns ON but not ankle/relax on a relax board

This might be because the pin mapping for ethercat leds are not the same between the 2 boards. Technically, you should be able to flash product ankle on board relax even though you compiled it for board ankle as the mcu is the same, the user is responsible for flashing the right things on the right board.

**Review by cedricq — APPROVED** [review]

**Pull request merged**
